import S from '@sanity/desk-tool/structure-builder';
import { FaIcons, FaSearchengin, FaLandmark, FaRegThumbsUp, FaUsers, FaRegCopy, FaBlog, FaNewspaper, FaCalendarDay, FaPodcast, FaRegCreditCard, FaFileAlt, FaRegNewspaper, FaProjectDiagram, FaBullhorn, FaObjectGroup } from 'react-icons/fa';

const hiddenDocTypes = listItem =>
  !['seo', 'companyInfo', 'teamMember', 'page', 'icon', 'post', 'event', 'pressRelease', 'review', 'service', 'podcast', 'payment', 'gallery', 'banner', 'jumbotron']
    .includes(listItem.getId());

export default () =>
  S.list()
    .title('Content')
    .items([
      S.listItem()
        .title('Company')
        .child(
          S.editor()
            .id('companyInfo')
            .schemaType('companyInfo')
            .documentId('companyInfo')
        )
        .icon(FaLandmark),
      S.listItem()
        .title('Jumbotron')
        .child(
          S.editor()
            .id('jumbotron')
            .schemaType('jumbotron')
            .documentId('jumbotron')
            .title('Jumbotron')
        )
        .icon(FaObjectGroup),
      S.listItem()
        .title('Services')
        .schemaType('service')
        .child(S.documentTypeList('service').title('Services'))
        .icon(FaProjectDiagram),
      S.listItem()
        .title('Team')
        .schemaType('teamMember')
        .child(S.documentTypeList('teamMember').title('Team Members'))
        .icon(FaUsers),
      S.listItem()
        .title('Reviews')
        .schemaType('review')
        .child(S.documentTypeList('review').title('Reviews'))
        .icon(FaRegThumbsUp),
      S.listItem()
        .title('Podcasts')
        .schemaType('podcast')
        .child(S.documentTypeList('podcast').title('Podcasts'))
        .icon(FaPodcast),
      S.listItem()
        .title('Payments')
        .child(
          S.editor()
            .id('payment')
            .schemaType('payment')
            .documentId('payment')
            .title('Payments')
        )
        .icon(FaRegCreditCard),
      S.listItem()
        .title('Banner')
        .child(
          S.editor()
            .id('banner')
            .schemaType('banner')
            .documentId('banner')
            .title('Banner')
        )
        .icon(FaBullhorn),
      S.listItem()
        .title('News')
        .child(
          S.list()
            .title('Content types')
            .items([
              S.listItem()
                .title('Blog')
                .child(
                  S.documentTypeList('post').title('Posts')
                ).icon(FaBlog),
              S.listItem()
                .title('Press')
                .child(
                  S.documentTypeList('pressRelease').title('Press')
                ).icon(FaNewspaper),
              S.listItem()
                .title('Events')
                .child(
                  S.documentTypeList('event').title('Event')
                ).icon(FaCalendarDay)
            ])
        ).icon(FaRegNewspaper),
      S.listItem()
        .title('Pages')
        .child(
          S.list()
            .title('Pages')
            .items([
              S.listItem()
                .title('About')
                .child(
                  S.editor()
                    .id('aboutPage')
                    .schemaType('page')
                    .documentId('about')
                )
                .icon(FaFileAlt),
              S.listItem()
                .title('Services')
                .child(
                  S.editor()
                    .id('servicesPage')
                    .schemaType('page')
                    .documentId('services')
                )
                .icon(FaFileAlt),
              S.listItem()
                .title('Donate')
                .child(
                  S.editor()
                    .id('donatePage')
                    .schemaType('page')
                    .documentId('donate')
                )
                .icon(FaFileAlt),
              S.listItem()
                .title('Reviews')
                .child(
                  S.editor()
                    .id('reviewsPage')
                    .schemaType('page')
                    .documentId('reviews')
                )
                .icon(FaFileAlt),
              S.listItem()
                .title('Contact')
                .child(
                  S.editor()
                    .id('contactPage')
                    .schemaType('page')
                    .documentId('contact')
                )
                .icon(FaFileAlt),
              S.listItem()
                .title('News')
                .child(
                  S.editor()
                    .id('newsPage')
                    .schemaType('page')
                    .documentId('news')
                )
                .icon(FaFileAlt),
              S.listItem()
                .title('Team')
                .child(
                  S.editor()
                    .id('teamPage')
                    .schemaType('page')
                    .documentId('team')
                )
                .icon(FaFileAlt)
            ])
        ).icon(FaRegCopy),
      S.listItem()
        .title('SEO')
        .child(
          S.editor()
            .id('seo')
            .schemaType('seo')
            .documentId('seo')
            .title('Search Engine Optimization Metadata')
        )
        .icon(FaSearchengin),
      S.listItem()
        .title('Web Icons')
        .schemaType('icon')
        .child(S.documentTypeList('icon').title('FontAwesome Icons'))
        .icon(FaIcons),
      ...S.documentTypeListItems().filter(hiddenDocTypes)
    ]);
